name: ui-tests

on:

  push:
    paths:
      - "src/test/java/**/ui/**"
      - "src/test/java/**/config/**"
      - "src/test/java/**/testdata/**"
      - "src/test/resources/**"
      - "pom.xml"
      - ".github/workflows/ui-tests.yml"
  pull_request:
    paths:
      - "src/test/java/**/ui/**"
      - "src/test/java/**/config/**"
      - "src/test/java/**/testdata/**"
      - "src/test/resources/**"
      - "pom.xml"
      - ".github/workflows/ui-tests.yml"
  workflow_dispatch:


jobs:
  ui:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:4.23.1
        ports:
          - 4444:4444

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '24'
          cache: maven

      - name: Run tests (remote + headless)
        run: mvn -q clean test -Dgroups=ui -Dselenide.remote=http://localhost:4444/wd/hub -Dselenide.headless=true

      - name: Generate Allure report
        if: always()
        run: mvn -q allure:report

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-artifacts
          path: |
            target/surefire-reports/
            target/allure-results/
            target/site/allure-maven-plugin/